name: Acceptance

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test --logger "trx;logfilename=RocketSilo.Api.trx" src/RocketSilo.Api/RocketSilo.Api.Tests.csproj
      - uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Tests
          path: 'src/RocketSilo.Api/TestResults/*.trx'
          reporter: dotnet-trx
