name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Setup Variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/v}
        shell: bash
      - name: Restore .NET dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release -p:Version="${{ steps.vars.outputs.version }}" -p:PackageVersion="${{ steps.vars.outputs.version }}" src/RocketSilo.Api/RocketSilo.Api.csproj
      - name: Run Tests
        run: dotnet test --logger "trx;logfilename=Decknight.Commons.Tests.trx" --configuration Debug tests/RocketSilo.Api.Tests/RocketSilo.Api.Tests.csproj
      - uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Tests
          path: 'tests/RocketSilo.Api.Tests/TestResults/*.trx'
          reporter: dotnet-trx
      - name: Publish NuGet
#        run: dotnet nuget push src/RocketSilo.Api/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/DanielWare/index.json
        run: dotnet nuget push src/RocketSilo.Api/bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
